export const patientGuide = {
    title:'Saç Ekimi Öncesinde Ve Sonrasında Hasta Bilgilendirme Rehberi',
    desc:`
    <ol style="margin-left: 40px ">
    <li class="p3" style="line-height: 2;"><strong>Sa&ccedil; ekimi operasyonu &ouml;ncesi mevcut sağlık sorunlarınız ve kullandığınız ila&ccedil;lar ile ilgili danışanınızı bilgilendirmelisiniz.</strong></li>
    <li class="p3" style="line-height: 2;"><strong>Doktorunuzun onayı ile en az 3 g&uuml;n &ouml;nce Aspirin ve benzeri kan sulandırıcı ila&ccedil;larınızı almaya ara vermelisiniz.</strong>&nbsp;</li>
    <li class="p3" style="line-height: 2;"><strong>Ekim yapılan alan korunmalıdır.</strong> Ekilen k&ouml;klerin tutunma s&uuml;resi 3 g&uuml;nd&uuml;r. Bu sebeple sa&ccedil; ekiminden sonraki ilk 3 g&uuml;n ekim yapılan alana hi&ccedil;bir temasın olmaması &ccedil;ok &ouml;nemlidir. (&Ccedil;arpma, vurma, dokunma, kaşıma vb.)</li>
    <li class="p3" style="line-height: 2;"><strong>Fermuarlı veya d&uuml;ğmeli kıyafetler tercih edilmelidir.</strong> Baş kısmından kolay ge&ccedil;ecek kıyafetler tercih edilmelidir.<span class="Apple-converted-space">&nbsp;&nbsp;</span>Sa&ccedil; ekim b&ouml;lgenize gelebilecek herhangi bir darbe veya s&uuml;rtme o b&ouml;lgedeki sa&ccedil; k&ouml;klerinizi kaybetmenize neden olabilir.&nbsp;</li>
    <li class="p3" style="line-height: 2;"><strong>Baş, yere doğru ve hızlıca eğilmemelidir.</strong> Sa&ccedil; ekimi sonrası 3 g&uuml;n boyunca boyundan yere eğilmeyi gerektiren durumlarda dizlerin &uuml;zerine &ccedil;&ouml;kerek yere eğilme sağlanmalıdır.</li>
    <li class="p3" style="line-height: 2;"><strong>Sa&ccedil; ekimi sonrası soğuk kompres yapılmalıdır.&nbsp;</strong>Operasyon sonrası 2. Ve 7. G&uuml;n arası y&uuml;z şişmesi meydana gelebilir. Alında veya g&ouml;z &ccedil;evresinde şişliği en aza indirmek i&ccedil;in her saat 15 dakika kaşların &uuml;zerine buz torbası uygulayabilirsiniz.</li>
    <li class="p3" style="line-height: 2;"><strong>Uyku halinde boyun yastığı kullanılmalıdır.&nbsp;</strong>45 derece y&uuml;ksekte ve sırt &uuml;st&uuml; uyunmalıdır.<strong>&nbsp;</strong></li>
    <li class="p3" style="line-height: 2;"><strong>Sa&ccedil; ekimi sonrası, don&ouml;r ve ekim alanını kaşımaktan ka&ccedil;ınılmalıdır.&nbsp;</strong>İyileşmeyi geciktirebileceği ve ekilen sa&ccedil; k&ouml;klerine zarar verebileceği i&ccedil;in 1 ay boyunca sa&ccedil; derisini tırnakla kaşımak yerine o b&ouml;lge nazik&ccedil;e ovalanabilir.&nbsp;</li>
    <li class="p3" style="line-height: 2;"><strong>Yoğun egzersizlerden ka&ccedil;ınılmalıdır.&nbsp;</strong>Y&uuml;r&uuml;y&uuml;ş, yoga gibi hafif egzersizler operasyon sonrası 4. G&uuml;nden, yoğun tempolu egzersizler 1. aydan sonra yapılabilir.</li>
    <li class="p3" style="line-height: 2;"><strong>G&uuml;neşten ka&ccedil;ınılmalıdır.</strong> Uzun s&uuml;re doğrudan g&uuml;neş ışınlarına maruz kalmak, ekim yapılan sa&ccedil; derisinin y&uuml;zeyine zarar verir. Operasyon sonrası sa&ccedil; derisi 2 ay g&uuml;neşten korunmalıdır.&nbsp;</li>
    <li class="p3" style="line-height: 2;"><strong>Sosyal aktivitelere ve kişisel bakıma dikkat edilmelidir.</strong><span class="Apple-converted-space">&nbsp;&nbsp;</span>Sa&ccedil; ekimi sonrası 1 ay boyunca hamam, buhar banyosu, sauna, havuz ve solaryum kullanımı kesinlikle olmamalıdır. T&uuml;m bu aktiviteler, terlemeyi ve enfeksiyon riskini arttırıp, sa&ccedil; k&ouml;klerine zarar verebilir.&nbsp;</li>
    <li class="p3" style="line-height: 2;"><strong>Kask veya şapka takmaktan ka&ccedil;ınılmalıdır.&nbsp;</strong>Operasyon sonrası kask veya şapka kullanımı, ekim b&ouml;lgesinin terleme sonucu enfeksiyon kapma riskini barındırdığı i&ccedil;in 1 ay boyunca kullanılmamalıdır.</li>
    <li class="p3" style="line-height: 2;"><strong>Makas ile sa&ccedil; kesimi yapılmalıdır.&nbsp;</strong>Ense b&ouml;lgesine (don&ouml;r b&ouml;lgesine) 3 ay, ekim yapılan b&ouml;lgeye 6 ay boyunca tıraş makinesi, ustura veya jilet kullanılmamalıdır.&nbsp;</li>
    <li class="p3" style="line-height: 2;"><strong>Sa&ccedil; ekimi sonrası sa&ccedil; derisinde uyuşma olabilir.&nbsp;</strong>3 hafta i&ccedil;inde normale d&ouml;ner ancak bazen 2 ila 6 hafta s&uuml;rebilir. Duyusal sinirlerin yenilenmesi ile bu his ortadan kalkar.</li>
    <li class="p3" style="line-height: 2;"><strong>Sigara kullanılmamalıdır.&nbsp;</strong>Nikotin kan damarlarını sertleştirir ve daraltır.<strong>&nbsp;</strong>İyileşme s&uuml;resini uzattığı i&ccedil;in operasyon &ouml;ncesi ve sonrası en az 1 hafta sigara kullanmamak sizlerin yararına olacaktır.&nbsp;</li>
    <li class="p3" style="line-height: 2;"><strong>Alkol kullanılmamalıdır.<span class="Apple-converted-space">&nbsp;&nbsp;</span></strong>Kan basıncının normale d&ouml;nmesi ve v&uuml;cutta varolan alkol&uuml;n atılması i&ccedil;in operasyon &ouml;ncesi ve sonrası en az 2 hafta alkoll&uuml; i&ccedil;ecek t&uuml;ketilmemelidir.</li>
</ol>
    `

}
